config/routes.rb
Rinity::Application.routes.draw do
  resources :reservations

  resources :cars

  resources :users do
    member do
      get 'notify'
    end
  end

  resources :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  set_rgeo_factory_for_column(:start, RGeo::Geographic.spherical_factory(:srid => 4326))
  set_rgeo_factory_for_column(:destination, RGeo::Geographic.spherical_factory(:srid => 4326))

  belongs_to :user
  belongs_to :car
  has_many :reservations
  has_many :passengers, :class_name => "User", :foreign_key => "passenger_id", :through => :reservations, :conditions => "reservations.is_accepted = true"

  attr_accessible :destination, :destination_address, :is_recurring, :available_seats, :price, :start, :start_address, :trip_date, :user_id
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
    <% if @trip.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

          <ul>
            <% @trip.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :start_address %>
      <br/>
      <%= f.text_field :start_address %>
    </div>
    <div class="field">
      <%= f.label :destination_address %>
      <br/>
      <%= f.text_field :destination_address %>
    </div>
    <div class="field">
      <%= f.label :trip_date %>
      <br/>
      <%= f.datetime_select :trip_date %>
    </div>
    <div class="field">
      <%= f.label :is_recurring %>
      <br/>
      <%= f.check_box :is_recurring %>
    </div>
    <div class="field">
      <%= f.label :available_seats %>
      <br/>
      <%= f.number_field :available_seats %>
    </div>
    <div class="field">
      <%= f.label :price %>
      <br/>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :user_id %>
      <br/>
      <%= f.number_field :user_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Start address</th>
    <th>Destination address</th>
    <th>Trip date</th>
    <th>Is recurring</th>
    <th>Available seats</th>
    <th>Price</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.start_address %></td>
        <td><%= trip.destination_address %></td>
        <td><%= trip.trip_date %></td>
        <td><%= trip.is_recurring %></td>
        <td><%= trip.avalable_seats %></td>
        <td><%= trip.price %></td>
        <td><%= trip.user_id %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start address:</b>
  <%= @trip.start_address %>
</p>

<p>
  <b>Destination address:</b>
  <%= @trip.destination_address %>
</p>

<p>
  <b>Trip date:</b>
  <%= @trip.trip_date %>
</p>

<p>
  <b>Is recurring:</b>
  <%= @trip.is_recurring %>
</p>

<p>
  <b>Available seats:</b>
  <%= @trip.available_seats %>
</p>

<p>
  <b>Price:</b>
  <%= @trip.price %>
</p>

<p>
  <b>User:</b>
  <%= @trip.user_id %>
</p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>