config/routes.rb
Rinity::Application.routes.draw do
  resources :reservations

  resources :cars

  resources :users do
    member do
      get 'notify'
    end
  end

  resources :trips

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :trip
  belongs_to :passenger, :class_name => "User", :foreign_key => "passenger_id"
  belongs_to :car
  attr_accessible :trip_id, :is_accepted, :passenger_id, :seat
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
    <% if @reservation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

          <ul>
            <% @reservation.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :trip_id %>
      <br/>
      <%= f.number_field :trip_id %>
    </div>
    <div class="field">
      <%= f.label :passenger_id %>
      <br/>
      <%= f.number_field :passenger_id %>
    </div>
    <div class="field">
      <%= f.label :seat %>
      <br/>
      <%= f.number_field :seat %>
    </div>
    <div class="field">
      <%= f.label :is_accepted %>
      <br/>
      <%= f.check_box :is_accepted %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>Car</th>
    <th>Passenger</th>
    <th>Seat</th>
    <th>Is accepted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.trip_id %></td>
        <td><%= reservation.passenger_id %></td>
        <td><%= reservation.seat %></td>
        <td><%= reservation.is_accepted %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Car:</b>
  <%= @reservation.trip_id %>
</p>

<p>
  <b>Passenger:</b>
  <%= @reservation.passenger_id %>
</p>

<p>
  <b>Seat:</b>
  <%= @reservation.seat %>
</p>

<p>
  <b>Is accepted:</b>
  <%= @reservation.is_accepted %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>